"""Add users table

Revision ID: 453556bbb96a
Revises: 1a90e6ba6220
Create Date: 2025-01-19 16:59:37.185115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453556bbb96a'
down_revision: Union[str, None] = '1a90e6ba6220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_owner_id_fkey', 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('contacts_owner_id_fkey', 'contacts', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
